metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: train.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: val.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: val.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
